/*
randomness: 9045282
cases: []
*/

program hash_into_struct.aleo;

struct arjQITzQAw:
    qcoZ_qzzye as boolean;
    ynh0UgMeBB as address;
    uLpRnfnsg9 as u8;
    D4j4T0s8Kc as boolean;
    MaDEhMWsdd as u8;
    HpHdqmODmR as i64;
    rnbm6ct6qw as u16;

closure kmNSyjzeaZ:
    input r0 as boolean;
    hash.bhp768 5372560835405554868775356124803982999725684598186573362469277964967083823207field into r1 as arjQITzQAw;
    output r1.qcoZ_qzzye as boolean;

function uftFRlQzED:
    input r0 as boolean.private;
    output r0 as boolean.private;
